service: monitoring-frontend-app

plugins:
  - serverless-single-page-app-plugin
  - serverless-plugin-tracing
  - '@anttiviljami/serverless-stack-output'
  - serverless-scriptable-plugin
  - serverless-s3-remover

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  currentRegion: ${file(../services/monitoring-common/environment/config.${self:custom.currentStage}.json):region}

  monitoringCommonServiceName: ${file(../services/monitoring-common/serverless.yml):service}

  s3Bucket: monitoring-frontend-app-bucket-${self:custom.currentStage}

  output:
    handler: ./scripts/stackOutput.handler

  scriptHooks:
    after:deploy:finalize:
      - scripts/envSetup.js

  remover:
    buckets:
      - ${self:custom.s3Bucket}

provider:
  name: aws
  stage: ${self:custom.currentStage}
  region: ${self:custom.currentRegion}

  logRetentionInDays: 7

  tracing: true # enable tracing
  iamRoleStatements:
    - Effect: 'Allow' # xray permissions (required)
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - '*'

resources:
  - ${file(resources/cloudfront.yml)}
  - ${file(resources/cognito.yml)}
